# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    #     
    # STYLES     
    # 
    styleLineEditOk = ("QLineEdit{\n"
                        "    border: 2px solid rgb(45, 45, 45);\n"
                        "    border-radius: 5px;\n"
                        "    padding: 15px;    \n"
                        "    background-color: rgb(30, 30, 30);\n"
                        "    color: rgb(100, 100, 100);\n"
                        "}\n"
                        "\n"
                        "QLineEdit:hover{\n"
                        "    border: 2px solid rgb(65, 65, 65);\n"
                        "}\n"
                        "\n"
                        "QLineEdit:focus{\n"
                        "    border: 2px solid rgb(255, 207, 0);\n"
                        "    color: rgb(200, 200, 200);\n"
                        "}")
    styleLineEditError = ("QLineEdit{\n"
                        "    border: 2px solid rgb(255, 85, 127);\n"
                        "    border-radius: 5px;\n"
                        "    padding: 15px;    \n"
                        "    background-color: rgb(30, 30, 30);\n"
                        "    color: rgb(100, 100, 100);\n"
                        "}\n"
                        "\n"
                        "QLineEdit:hover{\n"
                        "    border: 2px solid rgb(255, 85, 127);\n"
                        "}\n"
                        "\n"
                        "QLineEdit:focus{\n"
                        "    border: 2px solid rgb(255, 207, 0);\n"
                        "    color: rgb(200, 200, 200);\n"
                        "}")

    stylePopupError = ("background-color: rgb(255, 85, 127); border-radius: 5px;")
    stylePopupOk = ("background-color: rgb(0, 255, 123); border-radius: 5px;")

    #     
    # FUNCTIONS
    #     

    def checkFields(self):
        textUser = ''
        textPassword = ''

        def showMessage(message):
                self.frame_error.show()
                self.label_error.setText(message)

        # CHECK USER
        if not self.text_user.text():
            textUser = ' Usuário Vazio '
            self.text_user.setStyleSheet(self.styleLineEditError)

        else:
            textUser = ''
            self.text_user.setStyleSheet(self.styleLineEditOk)

        # CHECK PASSWORD
        if not self.textPassword.text():
            textPassword = ' Senha vazia '
            self.textPassword.setStyleSheet(self.styleLineEditError)
        else:
            textPassword = ''
            self.textPassword.setStyleSheet(self.styleLineEditOk)

        # CHECK FIELDS
        if textUser + textPassword != '':
            self.frame_error.setStyleSheet(self.stylePopupError)
            text = textUser + textPassword
            showMessage(text)
        else:
            text = 'LOGIN: OK'
            self.frame_error.setStyleSheet(self.stylePopupOk)
            if self.checkBox_save_user.isChecked():
                text = text + ' | USUÁRIO SALVO: OK' 
            showMessage(text)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 939)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error.setStyleSheet(self.stylePopupError)
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_close_popup = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_close_popup.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_popup.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-position: center;\n"
"    background-color: rgb(50, 50, 50);    \n"
"    background-image: url(:/close_image/Images/cil-x.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(38, 38, 38);\n"
"    color: #fff;\n"
"}")
        self.pushButton_close_popup.setText("")
        self.pushButton_close_popup.setObjectName("pushButton_close_popup")
        self.horizontalLayout_3.addWidget(self.pushButton_close_popup)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("background-repeat: no-repeat;\n"
"background-position: center;\n"
"border-radius: 2px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.img_logo = QtWidgets.QFrame(self.login_area)
        self.img_logo.setGeometry(QtCore.QRect(45, 40, 360, 90))
        self.img_logo.setStyleSheet("background-image: url(:/logo/Images/logo_360x90.png);")
        self.img_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_logo.setObjectName("img_logo")
        self.avatar = QtWidgets.QFrame(self.login_area)
        self.avatar.setGeometry(QtCore.QRect(160, 146, 120, 120))
        self.avatar.setStyleSheet("QFrame{    \n"
"    background-image: url(:/avatar/Images/avatar.png);\n"
"    border-radius: 60px;\n"
"    border: 5px solid rgb(255, 207, 0);\n"
"}")
        self.avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setObjectName("avatar")
        self.text_user = QtWidgets.QLineEdit(self.login_area)
        self.text_user.setGeometry(QtCore.QRect(85, 293, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.text_user.setFont(font)


        self.text_user.setStyleSheet(self.styleLineEditOk)
        

        self.text_user.setMaxLength(32)
        self.text_user.setObjectName("text_user")
        self.textPassword = QtWidgets.QLineEdit(self.login_area)
        self.textPassword.setGeometry(QtCore.QRect(85, 349, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.textPassword.setFont(font)
        self.textPassword.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;    \n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(65, 65, 65);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.textPassword.setMaxLength(16)
        self.textPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textPassword.setObjectName("textPassword")
        self.checkBox_save_user = QtWidgets.QCheckBox(self.login_area)
        self.checkBox_save_user.setGeometry(QtCore.QRect(85, 413, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_save_user.setFont(font)
        self.checkBox_save_user.setStyleSheet("QCheckBox::indicator{\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-top: 2px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    border: 2px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"} ")
        self.checkBox_save_user.setObjectName("checkBox_save_user")
        self.pushButton_login = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login.setGeometry(QtCore.QRect(85, 450, 280, 45))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid rgb(229, 183, 0);\n"
"    background-color: rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35)\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(75, 75, 75);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_2.addWidget(self.label_credits)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 
        # FUNCTIONS
        # 

        # BT CLOSE POPUP 
        self.pushButton_close_popup.clicked.connect(lambda: self.frame_error.hide())

        # HIDE ERROR
        self.frame_error.hide()

        # BT LOGIN
        self.pushButton_login.clicked.connect(self.checkFields)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "ERROR"))
        self.text_user.setPlaceholderText(_translate("MainWindow", "Digite seu nick..."))
        self.textPassword.setPlaceholderText(_translate("MainWindow", "Digite sua senha..."))
        self.checkBox_save_user.setText(_translate("MainWindow", "MANTENHA-ME CONECTADO"))
        self.pushButton_login.setText(_translate("MainWindow", "CONECTAR AO CYBERPUNK"))
        self.label_credits.setText(_translate("MainWindow", "Created by: Mateus Santos"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
